import React from 'react';

import styled from 'styled-components';

import { AdvantagesItem } from './AdvantagesItem';

import { advBorderImage } from '../../../assets/images';
import { Content } from '../../../components/Content';

export const AdvantagesBlock = () => {
  return (
    <Content>
      <Wrapper>
        <HeadBorder alt='Splitter' src={advBorderImage} />
        <WrapperItems>
          <AdvantagesItem
            text='Return up to 30% APY on in-game purchases'
            title='Play to Earn'
          />
          <AdvantagesItem
            text='Infinite replayability with content generated by AI'
            title='Power by AI'
          />
          <AdvantagesItem
            text='Learn about crypto domain while having fun'
            title='Play to Learn'
          />
        </WrapperItems>
      </Wrapper>
    </Content>
  );
};

const Wrapper = styled.div(({ theme }) => ({
  width: '100%',
  marginTop: '180px',
  paddingBottom: '24px',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  flexDirection: 'column' || theme.column,

  '@media screen and (max-width:1439px)': {
    marginTop: '88px',
  },

  '@media screen and (max-width:1024px)': {
    marginTop: '68px',
  },

  '@media screen and (max-width:768px)': {
    marginTop: '68px',
  },
}));

const HeadBorder = styled.img(() => ({
  maxWidth: '80%',
}));

const WrapperItems = styled.div(({ theme }) => ({
  marginTop: '52px',
  display: 'flex',
  gap: '110px',
  alignItems: 'flex-start',

  '@media screen and (max-width:1024px)': {
    gap: '50px',
    flexWrap: 'wrap' || theme?.wrap,
    justifyContent: 'center',
  },

  '@media screen and (max-width:768px)': {
    gap: '20px',
    marginTop: '57px',
  },
}));
