import React from 'react';

import styled from 'styled-components';

import { AdvantagesItem } from './AdvantagesItem';

import { advBorderImage } from '../../../assets/images';
import { Content } from '../../../components/Content';

export const AdvantagesBlock = () => {
  return (
    <Content>
      <Wrapper>
        <HeadBorder alt='advBorder' src={advBorderImage} />
        <WrapperItems>
          <AdvantagesItem
            text='Return up to 30% APY on everything you invest into the gameplay.'
            title='Play to Earn'
          />
          <AdvantagesItem
            text='Infinite replayability with random events and encounters generated by AI.'
            title='Power by AI'
          />
          <AdvantagesItem
            text='Learn about crypto domain while having fun.'
            title='Play to Learn'
          />
        </WrapperItems>
      </Wrapper>
    </Content>
  );
};

const Wrapper = styled.div(({ theme }) => ({
  width: '100%',
  marginTop: '180px',
  paddingBottom: '24px',
  display: 'flex',
  justifyContent: 'center',
  alignItems: 'center',
  flexDirection: 'column' || theme.column,
}));
const HeadBorder = styled.img(() => ({}));
const WrapperItems = styled.div(() => ({
  marginTop: '52px',
  display: 'flex',
  gap: '110px',
}));
