name: Pull Request Checks

on:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  pull-requests: read

jobs:
  pr-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm install

      - name: Lint
        run: npm run eslint

      - name: Build
        run: npm run build
